import type {Item} from './model';
export function businessDate(value:string){if(!value)return '';if(/^\d{4}-\d{2}-\d{2}$/.test(value))return value;const date=new Date(value);if(!Number.isFinite(date.getTime()))return '';const parts=new Intl.DateTimeFormat('en-CA',{timeZone:'America/Sao_Paulo',year:'numeric',month:'2-digit',day:'2-digit'}).formatToParts(date);return ['year','month','day'].map(k=>parts.find(p=>p.type===k)?.value).join('-');}
export const rowDate=(r:Item)=>r.data.date||businessDate(r.created);
export const refunded=(items:Item[],receipt:string)=>items.filter(r=>r.kind==='refund'&&r.data.receipt===receipt).reduce((s,r)=>s+r.data.amount,0);
export const receiptNet=(items:Item[],r:Item)=>r.data.amount-refunded(items,r.id);
export function chargeTotals(items:Item[],charge:Item){const gross=items.filter(r=>r.kind==='receipt'&&r.data.charge===charge.id).reduce((s,r)=>s+r.data.amount,0),refunds=items.filter(r=>r.kind==='refund'&&r.data.charge===charge.id).reduce((s,r)=>s+r.data.amount,0),paid=gross-refunds;return {gross,refunds,paid,balance:charge.data.cancelledAt?0:Math.max(0,charge.data.amount-paid)};}
export const outstanding=(items:Item[])=>items.filter(r=>r.kind==='charge').reduce((sum,c)=>sum+chargeTotals(items,c).balance,0);
export function monthLabel(month:string){return new Date(month+'-01T12:00:00').toLocaleDateString('pt-BR',{month:'long',year:'numeric'});}
export function addMonths(month:string,n:number){const [year,m]=month.split('-').map(Number);const date=new Date(Date.UTC(year,m-1+n,1));return date.toISOString().slice(0,7);}
export function financeSummary(items:Item[],month:string,today:string){const within=(r:Item)=>!month||rowDate(r).startsWith(month);const receipts=items.filter(r=>r.kind==='receipt'&&within(r)),refunds=items.filter(r=>r.kind==='refund'&&within(r)),expenses=items.filter(r=>r.kind==='expense'&&within(r)),charges=items.filter(r=>r.kind==='charge');const gross=receipts.reduce((s,r)=>s+r.data.amount,0),returned=refunds.reduce((s,r)=>s+r.data.amount,0),cost=expenses.reduce((s,r)=>s+r.data.amount,0),net=gross-returned;const inPeriodCharges=charges.filter(c=>!month||c.data.due?.startsWith(month));const future=Array.from({length:6},(_,index)=>{const period=addMonths(month||today.slice(0,7),index);return {month:period,total:charges.filter(c=>c.data.due?.startsWith(period)).reduce((s,c)=>s+chargeTotals(items,c).balance,0)};});
 const serviceMap=new Map<string,{name:string;count:number;revenue:number}>();for(const p of items.filter(r=>r.kind==='project'&&r.data.status!=='Cancelado'&&(!month||businessDate(r.created).startsWith(month)))){const name=p.data.type||'Sem modalidade';const old=serviceMap.get(name)||{name,count:0,revenue:0};old.count++;serviceMap.set(name,old);}for(const r of [...receipts,...refunds]){const p=items.find(p=>p.id===r.project&&p.kind==='project'),name=p?.data.type||'Sem modalidade',old=serviceMap.get(name)||{name,count:0,revenue:0};old.revenue+=r.kind==='refund'?-r.data.amount:r.data.amount;serviceMap.set(name,old);}return {receipts,refunds,expenses,inPeriodCharges,gross,returned,cost,net,profit:net-cost,balance:inPeriodCharges.reduce((s,c)=>s+chargeTotals(items,c).balance,0),allBalance:outstanding(items),overdue:charges.filter(c=>c.data.due&&c.data.due<today).reduce((s,c)=>s+chargeTotals(items,c).balance,0),undated:charges.filter(c=>!c.data.due).reduce((s,c)=>s+chargeTotals(items,c).balance,0),future,services:[...serviceMap.values()].sort((a,b)=>b.count-a.count||b.revenue-a.revenue||a.name.localeCompare(b.name))};}
