import {store} from './firebase';
export const mailReady=()=>process.env.NOTIFICATIONS_ENABLED==='true'&&!!process.env.RESEND_API_KEY&&!!process.env.MAIL_FROM;
export type Job={id:string;project:string;recipient:string;member:string;event:string;status:string;attempts:number;created:string;nextAttemptAt:number;link:string;leaseUntil?:number};
export async function dispatchJob(job:Job,authorized:boolean,send:typeof fetch=fetch){if(!authorized)return {status:'cancelled',error:'Acesso revogado ou avisos desativados'};const response=await send('https://api.resend.com/emails',{method:'POST',headers:{Authorization:'Bearer '+process.env.RESEND_API_KEY,'Content-Type':'application/json','Idempotency-Key':'portal/'+job.id},body:JSON.stringify({from:process.env.MAIL_FROM,to:[job.recipient],subject:'Há uma atualização no seu projeto · Gabriel Gomes',text:'Olá! Há novidades no seu projeto. Entre no Portal com este mesmo e-mail para consultar a atualização:\n\n'+job.link+'\n\nVocê pode desativar os avisos nas preferências do Portal.\nGabriel Gomes'}) ,signal:AbortSignal.timeout(15000)});if(response.ok){const result=await response.json() as {id?:string};return {status:'sent',providerId:result.id||''};}const retry=response.status===429||response.status>=500;return {status:retry?'pending':'failed',error:'Provedor de e-mail: HTTP '+response.status};}
export async function processQueue(database?:ReturnType<typeof store>,send:typeof fetch=fetch){if(!mailReady())return {configured:false,processed:0};const db=database||store(),now=Date.now();const snap=await db.collection('portal_mail_jobs').where('nextAttemptAt','<=',now).limit(25).get();let processed=0;
 for(const doc of snap.docs){const job=await db.runTransaction(async tx=>{const s=await tx.get(doc.ref);const data=s.data() as Job|undefined;if(!data||!['pending','processing'].includes(data.status)||(data.leaseUntil||0)>Date.now())return null;if(Date.now()-Date.parse(data.created)>20*60*60*1000){tx.update(doc.ref,{status:'needs_review',nextAttemptAt:Number.MAX_SAFE_INTEGER,error:'Janela de envio expirou; conferir no provedor antes de reenviar.'});return null;}if(data.attempts>=5){tx.update(doc.ref,{status:'failed',nextAttemptAt:Number.MAX_SAFE_INTEGER,error:'Limite de tentativas atingido'});return null;}const leaseUntil=Date.now()+120000;tx.update(doc.ref,{status:'processing',attempts:data.attempts+1,leaseUntil,nextAttemptAt:leaseUntil});return {...data,attempts:data.attempts+1};});if(!job)continue;
 const [member,project]=await Promise.all([db.collection('portal_records').doc(job.member).get(),db.collection('portal_records').doc(job.project).get()]);const md=member.exists?JSON.parse(member.data()!.data):{},pd=project.exists?JSON.parse(project.data()!.data):{};const authorized=member.exists&&member.data()!.project===job.project&&String(md.email||'').toLowerCase()===job.recipient&&md.emailNotifications!==false&&project.exists&&!pd.archived;
 let result:{status:string;error?:string;providerId?:string};try{result=await dispatchJob(job,authorized,send);}catch{result={status:'pending',error:'Falha de conexão; aguardando nova tentativa.'};}if(result.status==='pending'&&job.attempts>=5)result.status='needs_review';await doc.ref.update({...result,...(result.status==='sent'?{error:''}:{}),leaseUntil:0,updated:new Date().toISOString(),nextAttemptAt:result.status==='pending'?Date.now()+Math.min(3600000,60000*2**job.attempts):Number.MAX_SAFE_INTEGER});processed++;
 }return {configured:true,processed};}
