import {createServer} from 'node:http';
import {readFile,stat} from 'node:fs/promises';
import {resolve,extname} from 'node:path';
import {Readable} from 'node:stream';
import {timingSafeEqual} from 'node:crypto';
import {requestContext} from './auth';
import {context,ApiError,respondError,mutationOrigin,db} from './domain';
import {store} from './firebase';
import {mailReady,processQueue} from './mail';
import * as data from '@/app/api/data/route';
import * as files from '@/app/api/files/route';
import * as commercial from '@/app/api/commercial/route';
import * as completion from '@/app/api/completion/route';
import * as finance from '@/app/api/finance/route';
import * as backup from '@/app/api/backup/route';
const publicDir=resolve(process.cwd(),'dist/client');
const routes:Record<string,Record<string,unknown>>={'/api/data':data,'/api/files':files,'/api/commercial':commercial,'/api/completion':completion,'/api/backup':backup,'/api/finance':finance};
function equal(a:string,b:string){const aa=Buffer.from(a),bb=Buffer.from(b);return aa.length===bb.length&&timingSafeEqual(aa,bb);}
async function handle(req:Request){const url=new URL(req.url),path=url.pathname,method=req.method;if(path==='/api/config'&&method==='GET'){return Response.json({firebase:{apiKey:process.env.FIREBASE_WEB_API_KEY,authDomain:process.env.FIREBASE_AUTH_DOMAIN,projectId:process.env.FIREBASE_PROJECT_ID,appId:process.env.FIREBASE_APP_ID},notificationsEnabled:process.env.NOTIFICATIONS_ENABLED==='true'});}
 if(path==='/healthz')return Response.json({ok:true});
 if(path==='/api/notifications/process'&&method==='POST'){const token=process.env.MAIL_JOB_TOKEN;if(!token||!equal(req.headers.get('authorization')||'','Bearer '+token))throw new ApiError(403,'Sem permissão.');return Response.json(await processQueue());}
 if(path==='/api/notifications/preferences'){const {user,items}=await context();const memberships=items.filter(r=>r.kind==='member'&&r.data.email.toLowerCase()===user.email.toLowerCase());if(method==='GET')return Response.json({enabled:memberships.every(r=>r.data.emailNotifications!==false),projects:memberships.length});if(method!=='PATCH')throw new ApiError(405,'Método inválido.');mutationOrigin(req);const b=await req.json();if(typeof b.enabled!=='boolean')throw new ApiError(400,'Preferência inválida.');await db().batch(memberships.map(r=>db().prepare('UPDATE records SET data=? WHERE id=?').bind(JSON.stringify({...r.data,emailNotifications:b.enabled}),r.id)));return Response.json({ok:true});}
 if(path==='/api/notifications'){const {user}=await context();if(!user.admin)throw new ApiError(403,'Ação exclusiva do administrador.');if(method==='POST'){mutationOrigin(req);return Response.json(await processQueue());}if(method!=='GET')throw new ApiError(405,'Método inválido.');const jobs=await store().collection('portal_mail_jobs').orderBy('created','desc').limit(40).get();return Response.json({configured:mailReady(),jobs:jobs.docs.map(d=>{const j=d.data();return {id:d.id,recipient:j.recipient,status:j.status,attempts:j.attempts,created:j.created,error:j.error||''};})});}
 if(path.startsWith('/api/')){const handler=routes[path]?.[method];if(typeof handler!=='function')throw new ApiError(404,'Rota não encontrada.');return handler(req) as Promise<Response>;}
 if(!['GET','HEAD'].includes(method))throw new ApiError(405,'Método inválido.');const relative=decodeURIComponent(path).replace(/^\/+/,''),candidate=resolve(publicDir,relative);if(candidate!==publicDir&&!candidate.startsWith(publicDir+'/'))throw new ApiError(404,'Não encontrado.');let file=candidate;try{if(!(await stat(file)).isFile())file=resolve(publicDir,'index.html');}catch{if(path.startsWith('/assets/'))throw new ApiError(404,'Não encontrado.');file=resolve(publicDir,'index.html');}const bytes=await readFile(file);const mime:Record<string,string>={'.html':'text/html; charset=utf-8','.js':'text/javascript; charset=utf-8','.css':'text/css; charset=utf-8','.svg':'image/svg+xml','.png':'image/png','.woff2':'font/woff2','.jpg':'image/jpeg'};return new Response(method==='HEAD'?null:bytes,{headers:{'Content-Type':mime[extname(file)]||'application/octet-stream','Cache-Control':file.endsWith('index.html')?'no-store':'public, max-age=3600'}});
}
const required=['FIREBASE_PROJECT_ID','FIREBASE_OWNER_UID','FIREBASE_STORAGE_BUCKET','FIREBASE_WEB_API_KEY','FIREBASE_AUTH_DOMAIN','FIREBASE_APP_ID','PORTAL_URL'];if(required.some(k=>!process.env[k]))throw Error('Configuração incompleta: '+required.filter(k=>!process.env[k]).join(', '));const origin=new URL(process.env.PORTAL_URL!).origin;if(!origin.startsWith('https://')&&!origin.startsWith('http://localhost:'))throw Error('PORTAL_URL precisa usar HTTPS (ou localhost para teste).');
const server=createServer(async(incoming,outgoing)=>{try{let size=0;const chunks:Buffer[]=[];for await(const chunk of incoming){size+=chunk.length;if(size>22*1024*1024)throw new ApiError(413,'Arquivo muito grande.');chunks.push(chunk);}const url=new URL(incoming.url||'/',origin),headers=new Headers();for(const [key,value] of Object.entries(incoming.headers))if(value!==undefined)headers.set(key,Array.isArray(value)?value.join(','):value);const request=new Request(url,{method:incoming.method,headers,...(!['GET','HEAD'].includes(incoming.method||'GET')?{body:Buffer.concat(chunks)}:{})});const response=await requestContext.run(request,async()=>{try{return await handle(request);}catch(e){return respondError(e);}});outgoing.statusCode=response.status;response.headers.forEach((v,k)=>outgoing.setHeader(k,v));outgoing.setHeader('X-Content-Type-Options','nosniff');outgoing.setHeader('Referrer-Policy','same-origin');if(response.body)Readable.fromWeb(response.body as any).pipe(outgoing);else outgoing.end();}catch(e){const r=respondError(e);outgoing.writeHead(r.status,{'Content-Type':'application/json'});outgoing.end(await r.text());}});
server.requestTimeout=120000;server.listen(Number(process.env.PORT||8080),'0.0.0.0',()=>console.log('Portal ready'));
