import {readFile,stat,realpath} from 'node:fs/promises';
import {resolve,sep} from 'node:path';
import {createHash} from 'node:crypto';
import {store,auth,storage} from '../server/firebase';
const file=process.argv[2];if(!file)throw Error('Uso: npm run import:backup -- /pasta-extraida/dados.json');if(process.env.NOTIFICATIONS_ENABLED==='true')throw Error('Desative NOTIFICATIONS_ENABLED durante a importação.');if(!process.env.FIREBASE_OWNER_UID)throw Error('Configure o UID do administrador.');const owner=await auth().getUser(process.env.FIREBASE_OWNER_UID);if(!owner.emailVerified)throw Error('Confirme o e-mail do administrador antes de importar.');const bytes=await readFile(file),backup=JSON.parse(bytes.toString());if(backup.format!=='gabriel-business-os'||backup.version!==1||!Array.isArray(backup.records)||!Array.isArray(backup.files))throw Error('Backup inválido.');const ids=new Set<string>();for(const row of backup.records){if(typeof row.id!=='string'||row.id.includes('/')||ids.has(row.id)||typeof row.kind!=='string'||!row.data||typeof row.data!=='object'||Array.isArray(row.data)||typeof row.created!=='string')throw Error('Registro inválido ou duplicado');ids.add(row.id);}for(const row of backup.records)if(row.project&&!backup.records.some((p:any)=>p.id===row.project&&p.kind==='project'))throw Error('Projeto referenciado não encontrado');const base=await realpath(resolve(file,'..')),files=[];for(const f of backup.files){if(typeof f.key!=='string'||!f.key||typeof f.path!=='string'||!ids.has(f.id)||!backup.records.some((r:any)=>r.id===f.id&&r.kind==='document'&&r.data.file===f.key))throw Error('Referência de arquivo inválida');const path=await realpath(resolve(base,f.path));if(!path.startsWith(base+sep)||(await stat(path)).size>20*1024*1024)throw Error('Arquivo inválido');files.push({...f,local:path});}
const db=store(),hash=createHash('sha256').update(bytes).digest('hex'),lock=db.collection('portal_config').doc('migration');await db.runTransaction(async tx=>{const [prior,existing]=await Promise.all([tx.get(lock),tx.get(db.collection('portal_records').limit(1))]);if(prior.exists&&prior.data()!.hash!==hash)throw Error('Outra importação já foi iniciada');if(!prior.exists&&!existing.empty)throw Error('O destino precisa estar vazio');tx.set(lock,{hash,status:'importing',owner:owner.uid},{merge:true});});
for(const f of files)await storage().file(f.key).save(await readFile(f.local),{resumable:false,contentType:'application/octet-stream'});
for(let i=0;i<backup.records.length;i+=400){const batch=db.batch();for(const r of backup.records.slice(i,i+400))batch.set(db.collection('portal_records').doc(r.id),{...r,data:JSON.stringify(r.data)});await batch.commit();}
for(const a of backup.identityAliases||[])await db.collection('portal_identity_aliases').doc(createHash('sha256').update(a.email).digest('hex')).set(a);
await db.collection('portal_config').doc('workspace').set({id:'main',owner:owner.uid,sourceWorkspace:backup.workspace||[]});const check=await db.collection('portal_records').get();if(check.size!==backup.records.length)throw Error('Contagem divergente');for(const doc of check.docs){const expected=backup.records.find((r:any)=>r.id===doc.id);if(JSON.stringify(JSON.parse(doc.data().data))!==JSON.stringify(expected.data))throw Error('Dados divergentes');}for(const f of files){const [metadata]=await storage().file(f.key).getMetadata();if(Number(metadata.size)!==(await stat(f.local)).size)throw Error('Arquivo não conferido no destino');}await lock.set({hash,status:'complete',owner:owner.uid,completedAt:new Date().toISOString(),records:backup.records.length,files:files.length});console.log(JSON.stringify({imported:check.size,files:files.length,ownerEmail:owner.email}));
