import {useEffect,useState,FormEvent} from 'react';
import {initializeApp} from 'firebase/app';
import {getAuth,onAuthStateChanged,signInWithEmailAndPassword,signInWithPopup,GoogleAuthProvider,sendPasswordResetEmail,createUserWithEmailAndPassword,sendEmailVerification,signOut,User} from 'firebase/auth';
import PortalApp from '../shared/app/portal-app';
const originalFetch=window.fetch.bind(window);let auth:ReturnType<typeof getAuth>|undefined;
window.fetch=async(input,init)=>{const url=new URL(input instanceof Request?input.url:String(input),window.location.origin);if(url.origin===window.location.origin&&url.pathname.startsWith('/api/')&&auth?.currentUser){const headers=new Headers(input instanceof Request?input.headers:init?.headers);headers.set('Authorization','Bearer '+await auth.currentUser.getIdToken());return originalFetch(input,{...init,headers});}return originalFetch(input,init);};
export default function App(){const [ready,setReady]=useState(false),[user,setUser]=useState<User|null>(null),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[mode,setMode]=useState<'login'|'register'|'reset'>('login'),[message,setMessage]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[settings,setSettings]=useState(false),[enabled,setEnabled]=useState(true),[jobs,setJobs]=useState<any>(null);
 useEffect(()=>{let unsubscribe=()=>{};originalFetch('/api/config').then(r=>r.json()).then(c=>{auth=getAuth(initializeApp(c.firebase));auth.languageCode='pt-BR';unsubscribe=onAuthStateChanged(auth,u=>{setUser(u);setReady(true)});}).catch(()=>{setError('Não foi possível carregar a configuração do Portal.');setReady(true)});const logout=(e:MouseEvent)=>{const a=(e.target as HTMLElement).closest('a');if(a?.pathname==='/logout'){e.preventDefault();signOut(auth!);setSettings(false);setJobs(null);}};document.addEventListener('click',logout);return()=>{unsubscribe();document.removeEventListener('click',logout)};},[]);
 async function run(fn:()=>Promise<any>){setBusy(true);setError('');setMessage('');try{await fn();}catch(e:any){const code=e.code;setError(code==='auth/popup-closed-by-user'?'A janela de login foi fechada.':code==='auth/email-already-in-use'?'Este e-mail já possui uma conta. Use Entrar ou Recuperar senha.':code==='auth/weak-password'?'Use uma senha de pelo menos 8 caracteres.':'Não foi possível continuar. Confira os dados e tente novamente.');}finally{setBusy(false)}}
 async function submit(e:FormEvent){e.preventDefault();await run(async()=>{if(mode==='reset'){try{await sendPasswordResetEmail(auth!,email,{url:location.origin});}catch(e:any){if(e.code!=='auth/user-not-found')throw e;}setMessage('Se este e-mail tiver uma conta com senha, você receberá as instruções de recuperação.');return;}if(mode==='register'){if(password.length<8)throw {code:'auth/weak-password'};const result=await createUserWithEmailAndPassword(auth!,email,password);await sendEmailVerification(result.user,{url:location.origin});setMessage('Confirme seu e-mail pelo link enviado para liberar o login.');return;}await signInWithEmailAndPassword(auth!,email,password);});}
 async function openSettings(){setSettings(true);const res=await fetch('/api/notifications/preferences');if(res.ok)setEnabled((await res.json()).enabled);const admin=await fetch('/api/notifications');if(admin.ok)setJobs(await admin.json());}
 if(!ready)return <div className="login-state">Carregando Portal…</div>;
 if(user?.emailVerified)return <><PortalApp key={user.uid}/><button className="mail-preferences" onClick={()=>run(openSettings)}>Avisos por e-mail</button>{settings&&<div className="overlay"><section className="dialog" role="dialog" aria-modal="true" aria-label="Avisos por e-mail"><h2>Avisos por e-mail</h2><p>Os avisos chegam em {user.email}. Apenas mudanças visíveis nos seus projetos geram notificações.</p><label className="deletion-confirm"><input type="checkbox" checked={enabled} disabled={busy} onChange={e=>{const value=e.target.checked;run(async()=>{const r=await fetch('/api/notifications/preferences',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({enabled:value})});if(!r.ok)throw Error();setEnabled(value);setMessage('Preferência salva.');});}}/>Receber avisos dos projetos aos quais tenho acesso</label>{jobs&&<><p>{jobs.configured?'Serviço de e-mail configurado.':'Envio aguardando configuração do provedor de e-mail.'}</p><button disabled={busy||!jobs.configured} onClick={()=>run(async()=>{const r=await fetch('/api/notifications',{method:'POST'});if(!r.ok)throw Error();await openSettings();})}>Processar fila agora</button>{jobs.jobs.map((j:any)=><div className="list-row" key={j.id}><span>{j.recipient}</span><span>{({pending:'Na fila',processing:'Processando',sent:'Aceito pelo provedor',failed:'Falhou',cancelled:'Cancelado',needs_review:'Requer conferência'} as any)[j.status]}{j.error&&<small> · {j.error}</small>}</span></div>)}</>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<button onClick={()=>setSettings(false)}>Fechar</button></section></div>}</>;
 return <main className="login-state"><div className="eyebrow">Gabriel Gomes · Client Portal</div><h1>{user?'Confirme seu e-mail':mode==='reset'?'Recuperar senha':mode==='register'?'Criar acesso':'Entrar no Portal'}</h1>{user?<><p>Um link de confirmação deve ser enviado para {user.email}. Depois de confirmar, clique abaixo.</p><div className="toolbar"><button disabled={busy} onClick={()=>run(async()=>{await user.reload();await user.getIdToken(true);setUser(auth!.currentUser);if(auth!.currentUser?.emailVerified)location.reload();else setMessage('A confirmação ainda não foi identificada.');})}>Já confirmei meu e-mail</button><button disabled={busy} onClick={()=>run(()=>sendEmailVerification(user,{url:location.origin}))}>Reenviar confirmação</button><button onClick={()=>signOut(auth!)}>Sair</button></div></>:<><p>Use o mesmo e-mail autorizado para o seu projeto.</p><form onSubmit={submit}><label>E-mail<input type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)}/></label>{mode!=='reset'&&<label>Senha<input type="password" autoComplete={mode==='register'?'new-password':'current-password'} minLength={mode==='register'?8:undefined} required value={password} onChange={e=>setPassword(e.target.value)}/></label>}<button className="primary" disabled={busy||!auth}>{mode==='reset'?'Enviar instruções':mode==='register'?'Criar acesso':'Entrar'}</button></form>{mode==='login'&&<button className="button" disabled={busy||!auth} onClick={()=>run(()=>signInWithPopup(auth!,new GoogleAuthProvider()))}>Continuar com Google</button>}<div className="toolbar">{(['login','register','reset'] as const).filter(m=>m!==mode).map(m=><button key={m} disabled={busy} onClick={()=>{setMode(m);setError('');setMessage('')}}>{m==='login'?'Já tenho acesso':m==='register'?'Criar acesso':'Esqueci minha senha'}</button>)}</div><p className="muted">Criar uma conta não libera projetos automaticamente. Gabriel precisa autorizar o e-mail.</p></>}{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}</main>;
}
