import assert from 'node:assert/strict';
import {test} from 'node:test';
import {changedProject,recipients,Row} from '../server/events';
import {createDatabase} from '../server/database';
import {dispatchJob,Job} from '../server/mail';
import {FakeStore} from './fake-store';
const row=(id:string,kind:string,data:any,project:string|null='p'):Row=>({id,kind,project,created:'2026-10-06T12:00:00Z',data:JSON.stringify(data)});
test('public changes only; internal notes, private drafts and archive state are silent',()=>{assert.equal(changedProject(undefined,row('d','delivery',{visibility:'internal',description:'private'})),null);assert.equal(changedProject(undefined,row('d','delivery',{visibility:'published'})),'p');assert.equal(changedProject(row('p','project',{scope:'a',notes:'secret'}),row('p','project',{scope:'a',notes:'changed'})),null);assert.equal(changedProject(row('p','project',{scope:'a'}),row('p','project',{scope:'b'})),'p');assert.equal(changedProject(row('m','meeting',{visibility:'published',notes:'a'}),row('m','meeting',{visibility:'published',notes:'b'})),null);assert.equal(changedProject(row('p','project',{archived:false}),row('p','project',{archived:true})),null);assert.equal(changedProject(undefined,row('t','task',{title:'Internal'})),null);});
test('recipient isolation, deduplication and opt-out',()=>{const rows=[row('a','member',{email:'CLIENT@EXAMPLE.COM'}),row('b','member',{email:'client@example.com'}),row('c','member',{email:'disabled@example.com',emailNotifications:false}),row('d','member',{email:'other@example.com'},'other')];assert.deepEqual(recipients(rows,'p').map(r=>r.email),['client@example.com']);});
test('Firestore bridge creates events atomically; drafts silent; first access conditional; rollback',async()=>{process.env.NOTIFICATIONS_ENABLED='true';process.env.PORTAL_URL='https://portal.test';const fake=new FakeStore(),db=createDatabase(()=>fake as any);const add=(r:Row)=>db.prepare('INSERT INTO records(id,kind,project,data,created) VALUES(?,?,?,?,?)').bind(r.id,r.kind,r.project,r.data,r.created);await db.batch([add(row('p','project',{name:'P'},null)),add(row('member','member',{email:'client@example.com'}))]);await db.batch([add(row('d','delivery',{visibility:'internal',description:'Secret'}))]);assert.equal(fake.tables.get('portal_mail_jobs')?.size||0,0);await db.batch([db.prepare('UPDATE records SET data=? WHERE id=?').bind(JSON.stringify({visibility:'published',description:'Public'}),'d')]);assert.equal(fake.tables.get('portal_mail_jobs')?.size,1);const job=[...fake.tables.get('portal_mail_jobs')!.values()][0];assert.equal(job.recipient,'client@example.com');assert(!JSON.stringify(job).includes('Secret'));assert(!JSON.stringify(job).includes('Public'));const conditional="UPDATE records SET data=json_set(data,'$.firstAccessAt',?) WHERE id=? AND json_extract(data,'$.firstAccessAt') IS NULL";await db.batch([db.prepare(conditional).bind('first','member')]);await db.batch([db.prepare(conditional).bind('spoof','member')]);assert.equal(JSON.parse(fake.tables.get('portal_records')!.get('member').data).firstAccessAt,'first');await assert.rejects(()=>db.batch([add(row('x','update',{visibility:'published'})),add(row('d','delivery',{}))]));assert(!fake.tables.get('portal_records')!.has('x'));await db.batch([db.prepare('DELETE FROM records WHERE project=? OR id=?').bind('p','p')]);assert.equal(fake.tables.get('portal_records')!.size,0);});
test('mail sender omits content; one recipient; stable key; revoked access not sent; retry outcomes',async()=>{const job:Job={id:'stable',project:'p',recipient:'client@example.com',member:'m',event:'e',status:'pending',attempts:1,created:new Date().toISOString(),nextAttemptAt:0,link:'https://portal.test'};const requests:any[]=[];const send=async(url:any,options:any)=>{requests.push({url,options});return Response.json({id:'provider-id'});};assert.equal((await dispatchJob(job,false,send as any)).status,'cancelled');assert.equal(requests.length,0);assert.equal((await dispatchJob(job,true,send as any)).status,'sent');await dispatchJob(job,true,send as any);assert.equal(requests[0].options.headers['Idempotency-Key'],requests[1].options.headers['Idempotency-Key']);const body=JSON.parse(requests[0].options.body);assert.deepEqual(body.to,['client@example.com']);assert(!body.html);assert.equal((await dispatchJob(job,true,(async()=>new Response('',{status:429})) as any)).status,'pending');assert.equal((await dispatchJob(job,true,(async()=>new Response('',{status:400})) as any)).status,'failed');});

import {authenticate,requestContext} from '../server/auth';
test('identity rejects spoofed headers, unverified email and invalid tokens',async()=>{const verify=async(token:string)=>({uid:'firebase-uid',email:'Client@Example.com',email_verified:token==='verified'});assert.equal(await authenticate(new Request('https://portal.test',{headers:{'oai-authenticated-user-email':'owner@example.com'}}),verify),null);assert.equal(await authenticate(new Request('https://portal.test',{headers:{Authorization:'Bearer unverified'}}),verify),null);assert.equal((await authenticate(new Request('https://portal.test',{headers:{Authorization:'Bearer verified'}}),verify))?.userId,'firebase-uid');assert.equal(await authenticate(new Request('https://portal.test',{headers:{Authorization:'Bearer invalid'}}),async()=>{throw Error()}),null);});
test('concurrent stale writes are rejected before committing',async()=>{const fake=new FakeStore(),db=createDatabase(()=>fake as any),req=new Request('https://portal.test');await fake.collection('portal_records').doc('p').set(row('p','project',{scope:'old'},null));await requestContext.run(req,async()=>{await db.prepare('SELECT * FROM records ORDER BY created DESC').all();await fake.collection('portal_records').doc('p').set(row('p','project',{scope:'changed'},null));await assert.rejects(()=>db.batch([db.prepare('UPDATE records SET data=? WHERE id=?').bind(JSON.stringify({scope:'stale'}),'p')]),/outra sessão/);assert.equal(JSON.parse(fake.tables.get('portal_records')!.get('p').data).scope,'changed');});});
