import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {DatabaseSync} from 'node:sqlite';
import {createRequire} from 'node:module';
import {randomUUID} from 'node:crypto';
import ts from 'typescript';
const database=new DatabaseSync(':memory:');
for(const sql of readFileSync('drizzle/0000_ambiguous_the_spike.sql','utf8').split('--> statement-breakpoint'))database.exec(sql);
for(const sql of readFileSync('drizzle/0001_complex_spiral.sql','utf8').split('--> statement-breakpoint'))database.exec(sql);
const wrap=(sql,args=[])=>({bind(...a){return wrap(sql,a)},async all(){return {results:database.prepare(sql).all(...args)}},async first(){return database.prepare(sql).get(...args)||null},async run(){return {meta:{changes:database.prepare(sql).run(...args).changes}}},sql,args});
const databaseBinding={prepare:sql=>wrap(sql),async batch(stmts){database.exec('BEGIN');try{const results=[];for(const s of stmts)results.push(await s.run());database.exec('COMMIT');return results;}catch(e){database.exec('ROLLBACK');throw e}}};
function compile(path,imports={}){const src=ts.transpileModule(readFileSync(path,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const module={exports:{}};new Function('require','module','exports','crypto',src)(key=>imports[key]??createRequire(import.meta.url)(key),module,module.exports,{randomUUID});return module.exports;}
const dates=compile('lib/dates.ts');
assert.equal(dates.fromBrazilianDate('04/10/2026'),'2026-10-04');
assert.equal(dates.fromBrazilianDate('04/10/2026 14:30',true),'2026-10-04T14:30');
assert.equal(dates.toBrazilianDate('2026-10-04T14:30',true),'04/10/2026 14:30');
assert.equal(dates.fromBrazilianDate('31/02/2026'),null);
assert.equal(dates.fromBrazilianDate('29/02/2024'),'2024-02-29');
assert.equal(dates.fromBrazilianDate('29/02/2026'),null);
assert.equal(dates.fromBrazilianDate('04/10/2026 25:30',true),null);
assert.equal(dates.fromBrazilianDate('04/10/2026 14:65',true),null);
assert.equal(dates.fromBrazilianDate(''),'');
const agenda=compile('lib/agenda.ts');
const appointments=[{id:'meeting-a',kind:'meeting',project:'p1',data:{title:'Meeting',date:'2026-10-04T14:00'}},{id:'lead-a',kind:'lead',data:{name:'Lead',callDate:'2026-10-04T10:00',callDone:false}},{id:'lead-b',kind:'lead',data:{name:'Done',callDate:'2026-10-05T10:00',callDone:true}},{id:'past',kind:'meeting',project:'p2',data:{title:'Past',date:'2026-10-03T10:00'}}];
assert.equal(agenda.agendaEntries(appointments).length,4);
assert.deepEqual(agenda.nextAppointments(appointments,'2026-10-04T09:00').map(r=>r.id),['lead-a','meeting-a']);
assert.deepEqual(agenda.nextAppointments(appointments,'2026-10-04T11:00').map(r=>r.id),['meeting-a']);
const months=agenda.appointmentMonths([...agenda.agendaEntries(appointments),{id:'next-year',type:'Reunião',date:'2027-01-02T09:00',title:'Next year'},{id:'next-month',type:'Reunião',date:'2026-11-01T09:00',title:'Next month'}].reverse());
assert.deepEqual(months.map(r=>r.month),['2026-10','2026-11','2027-01']);
assert.deepEqual(months[0].appointments.map(r=>r.id),['past','lead-a','meeting-a','lead-b']);
assert.equal(months[0].label,'outubro de 2026');
const model=compile('lib/model.ts');
const financeModel=compile('lib/finance.ts');
const completionModel=compile('lib/completion.ts',{'./finance':financeModel});
const servicesModel=compile('lib/services.ts');
const commercialModel=compile('lib/commercial.ts',{'./model':model,'./services':servicesModel});
assert.equal(commercialModel.commercialStage({stage:'Novo lead',callDate:'2026-10-06T14:00'}),'Discovery agendada');
assert.equal(commercialModel.commercialStage({stage:'Discovery agendada',callDone:true}),'Discovery realizada');
assert.equal(commercialModel.commercialStage({stage:'Discovery realizada',proposalUrl:'https://example.com'}),'Proposta enviada');
assert.equal(commercialModel.commercialStage({stage:'Proposta enviada',proposalAccepted:true}),'Negociação');
assert.equal(commercialModel.commercialStage({stage:'Contrato',signed:true}),'Negociação');
let authHeaders=new Headers();
const auth=compile('app/chatgpt-auth.ts',{'next/headers':{headers:async()=>authHeaders},'next/navigation':{redirect(){throw Error('Unexpected login redirect')}},'cloudflare:workers':{env:{DB:databaseBinding}}});
assert.equal(await auth.getChatGPTUser(),null);
authHeaders=new Headers({'oai-authenticated-user-email':'verified@example.com'});
const legacyUser=await auth.requireChatGPTUser('/');
assert(legacyUser.userId && legacyUser.userId!=='verified@example.com');
assert.equal((await auth.getChatGPTUser()).userId,legacyUser.userId);
authHeaders.set('oai-authenticated-user-id','provider-stable-id');
assert.equal((await auth.getChatGPTUser()).userId,legacyUser.userId);
authHeaders=new Headers({'oai-authenticated-user-id':'second-provider-id','oai-authenticated-user-email':'second@example.com'});
assert.equal((await auth.getChatGPTUser()).userId,'second-provider-id');
let user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
const all=()=>database.prepare('SELECT * FROM records').all().map(r=>({...r,data:JSON.parse(r.data)}));
const stored=new Map();
const bucket={async put(k,v){stored.set(k,v)},async delete(k){stored.delete(k)},async get(k){return stored.has(k)?{body:stored.get(k)}:null}};
const server=compile('lib/server.ts',{'cloudflare:workers':{env:{DB:databaseBinding,BUCKET:bucket}},'@/app/chatgpt-auth':{async getChatGPTUser(){return user?{...user,userId:user.email,displayName:user.displayName}:null}},'./model':model});
const api=compile('app/api/data/route.ts',{'cloudflare:workers':{env:{BUCKET:bucket}},'@/lib/server':server,'@/lib/model':model,'@/lib/commercial':commercialModel,'@/lib/services':servicesModel,'@/lib/completion':completionModel,'@/lib/finance':financeModel});
async function call(method,body,url='https://site.test/api/data'){const res=await api[method](new Request(url,{method,headers:{'Content-Type':'application/json'},body:method==='GET'?undefined:JSON.stringify(body)}));return {status:res.status,...await res.json()}}
async function add(kind,data,project=null){const r=await call('POST',{kind,data,project});assert.equal(r.status,201,JSON.stringify(r));return r.item;}
assert.equal((await call('GET')).status,200);
const c=await add('client',{name:'Test',notes:'private'});
const p=await add('project',{name:'Project A',client:c.id,scope:'Scope',objective:'Goal',notes:'Private project notes'});
const p2=await add('project',{name:'Project B',client:c.id,scope:'Other'});
assert.equal(all().filter(r=>r.kind==='stage'&&r.project===p.id).length,6);
await add('task',{title:'Secret task',status:'Pendente'},p.id);
await add('meeting',{title:'Meeting',date:'2026-10-16T14:00',notes:'secret meeting',summary:'Shared summary',visibility:'published'},p.id);
const d=await add('delivery',{title:'Delivery',description:'Content',version:1,visibility:'published'},p.id);
await add('delivery',{title:'Draft',description:'Secret',version:2,visibility:'internal'},p.id);
const charge=await add('charge',{title:'Payment',amount:10000},p.id);
await add('receipt',{charge:charge.id,amount:4000,date:'2026-10-03'},p.id);
assert.equal((await call('POST',{kind:'receipt',project:p.id,data:{charge:charge.id,amount:7000}})).status,400);
assert.equal((await call('PATCH',{id:charge.id,data:{amount:3000}})).status,400);
const accessMember=await add('member',{name:'Client A',email:' CLIENT@example.com ',approver:true},p.id);
await call('GET',undefined,'https://site.test/api/data?view=client');
assert(!all().find(r=>r.id===accessMember.id).data.firstAccessAt,'Admin preview cannot confirm client access');

user={admin:false,email:'client@example.com',displayName:'Client A'};
const client=await call('GET');assert.equal(client.status,200);assert(!client.items.some(r=>r.id===p2.id));assert(!client.items.some(r=>r.kind==='task'));assert(!client.items.some(r=>r.data.title==='Draft'));assert(!client.items.find(r=>r.id===p.id).data.notes);assert(!client.items.find(r=>r.kind==='meeting').data.notes);assert(client.items.find(r=>r.kind==='meeting').data.summary);
const firstAccess=all().find(r=>r.id===accessMember.id).data.firstAccessAt;
assert(firstAccess);
await call('GET');assert.equal(all().find(r=>r.id===accessMember.id).data.firstAccessAt,firstAccess);
assert.equal((await call('PATCH',{id:charge.id,data:{amount:1}})).status,403);
assert.equal((await call('POST',{kind:'comment',project:p2.id,data:{delivery:d.id,text:'Forbidden'}})).status,403);
assert.equal((await call('POST',{kind:'task',project:p.id,data:{title:'Forbidden'}})).status,403);
const action=all().find(r=>r.kind==='action'&&r.project===p.id);
assert.equal((await call('PATCH',{id:action.id,data:{status:'Concluída'}})).status,400);
assert.equal((await call('PATCH',{id:action.id,data:{status:'Enviada',response:''}})).status,400);
assert.equal((await call('PATCH',{id:action.id,data:{status:'Enviada',response:'Materials and context',submittedBy:'Spoofed'}})).status,400);
assert.equal((await call('PATCH',{id:action.id,data:{status:'Enviada',response:'Materials and context'}})).status,200);
assert.equal(all().find(r=>r.id===action.id).data.submittedBy,'Client A');
assert.equal((await call('PATCH',{id:action.id,data:{status:'Enviada',response:'Duplicate'}})).status,409);
const approval=await add('approval',{delivery:d.id,decision:'approved',text:'Approved',author:'Spoofed'},p.id);assert.equal(approval.data.author,'Client A');
assert.equal((await call('POST',{kind:'approval',project:p.id,data:{delivery:d.id,decision:'changes',text:'Again'}})).status,409);
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
assert.equal((await call('PATCH',{id:d.id,data:{description:'Changed after approval'}})).status,400);
assert.equal((await call('DELETE',{id:approval.id})).status,400);
const change=await call('PATCH',{id:action.id,data:{status:'Pendente',reviewNote:'Please add references'}});assert.equal(change.status,200);
user={admin:false,email:'client@example.com',displayName:'Client A'};
assert.equal((await call('PATCH',{id:action.id,data:{status:'Enviada',response:'Added references'}})).status,200);
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
assert.equal((await call('PATCH',{id:action.id,data:{status:'Concluída',reviewNote:''}})).status,200);
user={admin:false,email:'client@example.com',displayName:'Client A'};
assert.equal((await call('PATCH',{id:action.id,data:{status:'Enviada',response:'After completion'}})).status,409);
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
const commercialApi=compile('app/api/commercial/route.ts',{'@/lib/server':server,'@/lib/model':model,'@/lib/commercial':commercialModel,'@/lib/services':servicesModel,'@/lib/completion':completionModel,'@/lib/finance':financeModel});
async function deal(action,lead,extra={}){const res=await commercialApi.POST(new Request('https://site.test/api/commercial',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,lead,...extra})}));return {status:res.status,...await res.json()};}
const lead=await add('lead',{name:'Lead',email:'client@example.com',stage:'Novo lead'});
assert.equal((await call('POST',{kind:'project',data:{name:'Premature',lead:lead.id}})).status,400);
assert.equal((await call('PATCH',{id:lead.id,data:{stage:'Ganho'}})).status,400);
assert.equal((await deal('close',lead.id,{confirm:true})).status,400);
assert.equal((await deal('convert',lead.id)).status,400);
assert.equal((await call('PATCH',{id:lead.id,data:{value:500000,service:'Communication Implementation',strategyValidated:'Sim',investigationNeeded:'Não',scope:'Landing page scope',objective:'Increase conversion',projectDue:'2026-11-01',proposalUrl:'https://example.com/proposal',sowUrl:'https://example.com/sow',contractUrl:'https://example.com/contract',proposalAccepted:true,signed:true,entry:true,entryAmount:200000,entryDate:'2026-10-04',balanceDue:'2026-11-01'}})).status,200);
assert.equal((await deal('close',lead.id)).status,400);
assert.equal((await deal('close',lead.id,{confirm:true})).status,200);
assert.equal((await call('PATCH',{id:lead.id,data:{value:1}})).status,400);
const converted=await deal('convert',lead.id,{client:c.id});assert.equal(converted.status,201);
const convertedRows=all().filter(r=>r.project===converted.project.id);assert.equal(convertedRows.filter(r=>r.kind==='document').length,3);assert.equal(convertedRows.filter(r=>r.kind==='stage').length,6);assert.equal(convertedRows.filter(r=>r.kind==='charge').reduce((s,r)=>s+r.data.amount,0),500000);assert.equal(convertedRows.filter(r=>r.kind==='receipt').reduce((s,r)=>s+r.data.amount,0),200000);assert(!convertedRows.some(r=>r.kind==='member'));
const beforeRetry=all().length;assert.equal((await deal('convert',lead.id)).existing,true);assert.equal(all().length,beforeRetry);
const noEntry=await add('lead',{name:'No entry client',email:'new-client@example.com',stage:'Proposta enviada',service:'Communication Audit',value:150000,proposalAccepted:true,requiresContract:false,requiresEntry:false,scope:'Audit',objective:'Assess message',projectDue:'2026-11-03'});assert.equal((await deal('close',noEntry.id,{confirm:true})).status,200);const beforeBadClient=all().length;assert.equal((await deal('convert',noEntry.id,{client:'missing-client'})).status,400);assert.equal(all().length,beforeBadClient);
const newDeal=await deal('convert',noEntry.id);assert.equal(newDeal.status,201);assert.equal(newDeal.client.data.email,'new-client@example.com');assert(!all().some(r=>r.kind==='receipt'&&r.project===newDeal.project.id));
const sameClient=await add('lead',{name:'Returning client',email:'NEW-CLIENT@example.com',stage:'Proposta enviada',service:'Communication Optimization',value:100000,proposalAccepted:true,requiresContract:false,requiresEntry:false,scope:'Optimization',objective:'Improve',projectDue:'2026-11-04'});await deal('close',sameClient.id,{confirm:true});const reused=await deal('convert',sameClient.id);assert.equal(reused.client.id,newDeal.client.id);
user={admin:false,email:'client@example.com',displayName:'Client A'};assert.equal((await deal('convert',lead.id)).status,403);user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
assert.equal((await call('POST',{kind:'project',data:{name:'Duplicate',lead:lead.id}})).status,409);

const files=compile('app/api/files/route.ts',{'cloudflare:workers':{env:{BUCKET:bucket}},'@/lib/server':server});
const fd=new FormData();fd.set('project',p.id);fd.set('title','Test file');fd.set('visibility','internal');fd.set('file',new File(['private file'], 'proof.txt',{type:'text/plain'}));const up=await files.POST(new Request('https://site.test/api/files',{method:'POST',body:fd}));assert.equal(up.status,201);const file=(await up.json()).item;
user={admin:false,email:'client@example.com',displayName:'Client A'};assert.equal((await files.GET(new Request('https://site.test/api/files?id='+file.id))).status,404);
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};await call('PATCH',{id:file.id,data:{visibility:'published'}});
user={admin:false,email:'client@example.com',displayName:'Client A'};const download=await files.GET(new Request('https://site.test/api/files?id='+file.id));assert.equal(download.status,200);assert.equal(await download.text(),'private file');
const anotherAction=all().find(r=>r.kind==='action'&&r.project===p2.id);
const foreign=new FormData();foreign.set('project',p.id);foreign.set('action',anotherAction.id);foreign.set('file',new File(['bad'],'bad.txt'));assert.equal((await files.POST(new Request('https://site.test/api/files',{method:'POST',body:foreign}))).status,400);
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
const materialRequest=await add('action',{title:'More materials',status:'Pendente'},p.id);
user={admin:false,email:'client@example.com',displayName:'Client A'};
const linked=new FormData();linked.set('project',p.id);linked.set('action',materialRequest.id);linked.set('file',new File(['brand material'],'brand.txt'));const linkedUpload=await files.POST(new Request('https://site.test/api/files',{method:'POST',body:linked}));assert.equal(linkedUpload.status,201);assert.equal((await linkedUpload.json()).item.data.action,materialRequest.id);
assert.equal((await call('PATCH',{id:materialRequest.id,data:{status:'Enviada',response:''}})).status,200);
user={admin:false,email:'other@example.com',displayName:'Other'};assert.equal((await call('GET')).status,403);
user=null;assert.equal((await call('GET')).status,401);
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
assert.equal((await call('PATCH',{id:accessMember.id,data:{approver:false,firstAccessAt:'spoofed'}})).status,200);
assert.equal(all().find(r=>r.id===accessMember.id).data.firstAccessAt,firstAccess);
const reader=await add('member',{name:'Reader',email:'reader@example.com',approver:false},p2.id);
assert.equal((await call('PATCH',{id:reader.id,data:{email:'client@example.com'}})).status,200,'Same email may access different projects');
assert.equal((await call('PATCH',{id:reader.id,data:{email:'reader@example.com'}})).status,200);
const otherReader=await add('member',{name:'Other',email:'other@example.com',approver:false},p2.id);
assert.equal((await call('PATCH',{id:otherReader.id,data:{email:'READER@example.com'}})).status,409);
const reviewable=await add('delivery',{title:'Reader delivery',description:'Shared',version:1,visibility:'published'},p2.id);
user={admin:false,email:'reader@example.com',displayName:'Reader'};
assert.equal((await call('GET')).status,200);
assert.equal((await call('POST',{kind:'approval',project:p2.id,data:{delivery:reviewable.id,decision:'approved'}})).status,403);
assert.equal((await call('POST',{kind:'comment',project:p2.id,data:{delivery:reviewable.id,text:'My comment'}})).status,201);
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
assert.equal((await call('PATCH',{id:reader.id,data:{email:'replacement@example.com'}})).status,200);
assert(!all().find(r=>r.id===reader.id).data.firstAccessAt,'Changed account must confirm its own access');
user={admin:false,email:'replacement@example.com',displayName:'Replacement'};
assert.equal((await call('GET')).status,200);
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
assert.equal((await call('DELETE',{id:reader.id})).status,200);
user={admin:false,email:'replacement@example.com',displayName:'Replacement'};
assert.equal((await call('GET')).status,403);
assert(all().some(r=>r.kind==='comment'&&r.data.text==='My comment'),'Revoking access preserves history');
// Architecture V2: qualification, legacy compatibility and a single integrated project.
assert.equal(model.pipelineStage('Contrato'),'Negociação');assert.equal(model.pipelineStage('Entrada'),'Negociação');assert.equal(model.pipelineStage('Diagnóstico Comercial Concluído'),'Qualificação / Escopo');assert.equal(model.pipelineLabel('Ganho'),'Fechado');
const qualification={communicationProblem:'Sim',investigationNeeded:'Sim',implementWithUs:'Sim',implementationPredictable:'Sim',operationalCapacity:'Sim'};
assert.equal(servicesModel.recommendPath(qualification),'Communication Project');
assert.equal(servicesModel.recommendPath({...qualification,implementWithUs:'Não'}),'Communication Audit');
assert.equal(servicesModel.recommendPath({...qualification,operationalCapacity:'Não'}),'Communication Audit');
assert.equal(servicesModel.recommendPath({...qualification,communicationProblem:'Não'}),'Não avançar');
assert.equal(servicesModel.recommendPath({communicationProblem:'Sim',investigationNeeded:'Não',strategyValidated:'Sim',implementWithUs:'Sim',needsRecurring:'Não'}),'Communication Implementation');
assert.equal(servicesModel.recommendPath({communicationProblem:'Sim',investigationNeeded:'Não',strategyValidated:'Sim',runningCommunication:'Sim',needsRecurring:'Sim'}),'Communication Optimization');
assert.equal(servicesModel.recommendPath({communicationProblem:'Sim',implementWithUs:'Sim'}),'','Incomplete context cannot default to Implementation');
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
const oldStages=all().filter(r=>r.kind==='stage'&&r.project===p.id);
const integrated=await add('lead',{name:'Integrated client',email:'integrated@example.com',stage:'Qualificação / Escopo',...qualification,recommendedPath:'Communication Project',qualificationDone:true,service:'Communication Project',value:870000,objective:'Solve communication problem',scope:'Integrated transformation',strategicScope:'Research and strategic direction',implementationScope:'Agreed assets',clientContact:'Responsible client',projectDue:'2026-12-01',proposalAccepted:true,requiresContract:false,requiresEntry:false,entryAmount:200000,entryDue:'2026-10-12',balanceDue:'2026-12-01'});
assert.equal(integrated.data.commercialVersion,2);assert.equal(integrated.data.integration,'Project-based');
assert.equal((await deal('close',integrated.id,{confirm:true})).status,200);
const convertedIntegrated=await deal('convert',integrated.id);assert.equal(convertedIntegrated.status,201);const ip=convertedIntegrated.project;
assert.equal(ip.data.type,'Communication Project');assert.equal(ip.data.strategicScope,'Research and strategic direction');assert.equal(ip.data.implementationScope,'Agreed assets');assert.equal(ip.data.clientContact,'Responsible client');
const stages=all().filter(r=>r.kind==='stage'&&r.project===ip.id).sort((a,b)=>a.data.order-b.data.order);assert.deepEqual(stages.map(r=>r.data.title),['Onboarding','Audit','Strategic Direction','Implementation','Review','Delivery','Offboarding']);
assert.equal(all().filter(r=>r.kind==='project'&&r.data.lead===integrated.id).length,1);assert.equal(all().filter(r=>r.kind==='action'&&r.project===ip.id&&r.data.purpose==='onboarding').length,1);assert.equal(all().filter(r=>r.kind==='charge'&&r.project===ip.id).reduce((s,r)=>s+r.data.amount,0),870000,'Value stays individually contracted, without bundle discounts');
const integratedCount=all().length;assert.equal((await deal('convert',integrated.id)).existing,true);assert.equal(all().length,integratedCount);
assert.deepEqual(all().filter(r=>r.kind==='stage'&&r.project===p.id),oldStages,'Existing stages are preserved');
const marker=await add('charge',{title:'Strategic phase milestone',amount:50000,milestone:stages[2].id},ip.id);assert.equal(marker.data.milestone,stages[2].id);
assert.equal((await call('POST',{kind:'charge',project:p.id,data:{title:'Foreign milestone',amount:100,milestone:stages[2].id}})).status,400);
assert.equal((await call('DELETE',{id:stages[2].id})).status,400);
const directIntegrated=await add('project',{name:'Direct integrated project',type:'Communication Project',strategicScope:'Strategy',implementationScope:'Execution',scope:'Custom scope',value:720000},null);assert.equal(all().filter(r=>r.kind==='stage'&&r.project===directIntegrated.id).length,7);
assert.equal((await call('POST',{kind:'project',data:{name:'Missing macro phases',type:'Communication Project'}})).status,400);
assert.equal((await call('POST',{kind:'project',data:{name:'Embedded fixed project',type:'Communication Audit',integration:'Recurring / Embedded'}})).status,400);
const uncertain=await add('lead',{name:'Uncertain execution',service:'Communication Implementation',investigationNeeded:'Sim',value:100000,scope:'Asset',objective:'Goal',projectDue:'2026-12-01',proposalAccepted:true,requiresEntry:false,requiresContract:false});assert.equal((await deal('close',uncertain.id,{confirm:true})).status,400);
const unfit=await add('lead',{name:'No fit',service:'Communication Audit',recommendedPath:'Não avançar',value:100000,scope:'Scope',objective:'Goal',projectDue:'2026-12-01',proposalAccepted:true,requiresEntry:false,requiresContract:false});assert.equal((await deal('close',unfit.id,{confirm:true})).status,400);
const incompleteProject=await add('lead',{name:'Missing qualification',service:'Communication Project',strategicScope:'Strategy',implementationScope:'Execution',value:100000,scope:'Scope',objective:'Goal',projectDue:'2026-12-01',proposalAccepted:true,requiresEntry:false,requiresContract:false});assert.equal((await deal('close',incompleteProject.id,{confirm:true})).status,400);
assert.equal(commercialModel.commercialStage({stage:'Discovery realizada',qualificationDone:true}),'Qualificação / Escopo');
assert.equal(commercialModel.commercialStage({stage:'Negociação',callDone:true}),'Negociação');
const legacy=server.record('lead',null,{name:'Legacy record',stage:'Entrada',service:'Communication Audit',value:100000,scope:'Scope',objective:'Goal',projectDue:'2026-12-01',proposalAccepted:true,requiresContract:false,requiresEntry:false});await server.statement(legacy).run();
assert.equal((await call('GET')).items.find(r=>r.id===legacy.id).data.stage,'Entrada','Read does not destructively migrate raw stages');assert.equal((await deal('close',legacy.id,{confirm:true})).status,200);
await add('member',{name:'Integrated client',email:'integrated@example.com',approver:true},ip.id);
user={admin:false,email:'integrated@example.com',displayName:'Integrated client'};
const projectView=await call('GET');assert.equal(projectView.items.find(r=>r.id===ip.id).data.implementationScope,'Agreed assets');assert.equal(projectView.items.filter(r=>r.kind==='stage').length,7);assert(!projectView.items.some(r=>r.kind==='lead'));assert.equal((await deal('close',uncertain.id,{confirm:true})).status,403);
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
const completionApi=compile('app/api/completion/route.ts',{'@/lib/server':server,'@/lib/completion':completionModel,'@/lib/finance':financeModel});
const backupApi=compile('app/api/backup/route.ts',{'@/lib/server':server});
async function finish(data){const res=await completionApi.POST(new Request('https://site.test/api/completion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)}));return {status:res.status,...await res.json()};}
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
const finishProject=await add('project',{name:'Finish project',status:'Ativo'},null);
const finalDoc=await add('document',{title:'Final guide',url:'https://example.com/guide',visibility:'published'},finishProject.id);
const privateDoc=await add('document',{title:'Private guide',url:'https://example.com/internal',visibility:'internal'},finishProject.id);
const completeData={project:finishProject.id,confirm:true,completionSummary:'Delivered work',handoverInstructions:'How to implement',nextSteps:'Measure results',finalMaterialIds:[finalDoc.id]};
assert.equal((await call('PATCH',{id:finishProject.id,data:{status:'Concluído'}})).status,400);
assert.equal((await finish(completeData)).status,400,'Pending checks require explicit agreement');
assert.equal((await finish({...completeData,completionCaveats:'Payment follows after handover',confirm:false})).status,400);
assert.equal((await finish({...completeData,completionCaveats:'Agreed',finalMaterialIds:[privateDoc.id]})).status,400);
assert.equal((await finish({...completeData,completionCaveats:'Agreed',finalMaterialIds:[d.id]})).status,400);
assert.equal((await finish({...completeData,completionCaveats:'Agreed',completionSummary:''})).status,400);
assert.equal((await finish({...completeData,completionCaveats:'Agreed'})).status,200);
const closed=all().find(r=>r.id===finishProject.id);assert.equal(closed.data.status,'Concluído');assert(closed.data.completedAt);assert.deepEqual(closed.data.finalMaterialIds,[finalDoc.id]);
assert.equal((await finish({...completeData,completionSummary:'changed'})).existing,true);
assert.equal((await call('PATCH',{id:finishProject.id,data:{name:'Renamed',completedAt:'spoofed',completionSummary:'spoofed'}})).status,200);
assert.equal(all().find(r=>r.id===finishProject.id).data.completionSummary,'Delivered work');
assert.equal((await call('DELETE',{id:finalDoc.id})).status,400);
assert.equal((await call('PATCH',{id:finalDoc.id,data:{visibility:'internal'}})).status,400);
await add('member',{name:'Final Client',email:'finish@example.com',approver:true},finishProject.id);
user={admin:false,email:'finish@example.com',displayName:'Final Client'};
assert.equal((await finish(completeData)).status,403);
assert.equal((await backupApi.GET()).status,403);
const finalView=await call('GET');assert(finalView.items.find(r=>r.id===finishProject.id).data.completionSummary);assert(!finalView.items.some(r=>r.id===privateDoc.id));
user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
const backupRes=await backupApi.GET();assert.equal(backupRes.status,200);const backup=await backupRes.json();assert.equal(backup.format,'gabriel-business-os');assert.equal(backup.records.length,all().length);assert(backup.files.length);assert(backup.identityAliases.length);assert(backup.workspace.length);
const lastVersion={id:'v-final',kind:'delivery',project:finishProject.id,created:'2026-10-04',data:{title:'Guide',version:2,visibility:'published'}},oldVersion={...lastVersion,id:'v-old',data:{...lastVersion.data,version:1}};
assert.equal(completionModel.completionChecks([oldVersion,lastVersion,{id:'a',kind:'approval',project:finishProject.id,data:{delivery:'v-old',decision:'approved'}}],finishProject.id)[0].done,false,'Only latest published version approval qualifies');
const {BackupZip}=compile('lib/backup-zip.ts');const zip=new BackupZip();zip.add('dados.json',new TextEncoder().encode(JSON.stringify(backup)));for(const f of backup.files)zip.add(f.path,new Uint8Array(stored.get(f.key)));
const {writeFileSync}=await import('node:fs');writeFileSync('/tmp/backup-zip-test.zip',Buffer.from(await zip.blob().arrayBuffer()));
console.log('PASS: commercial architecture V2, recommendation matrix, integrated project phases, historical preservation and milestone isolation; final delivery, closure permissions and history; complete admin backup; commercial closure gates, conversion, finance handoff, client reuse and duplicate protection; onboarding submission, review, complement and attachment isolation; project initialization; CRM conversion; durable SQL mutations; client isolation; internal notes; approval history; finance limits; upload and file permissions; authentication.');

const archiveProject=await add('project',{name:'Archive test',status:'Ativo'});const snapshot=all().filter(r=>r.project===archiveProject.id);assert.equal((await call('PATCH',{id:archiveProject.id,archived:true})).status,200);assert.equal(all().find(r=>r.id===archiveProject.id).data.archived,true);assert.equal((await call('PATCH',{id:archiveProject.id,data:{name:'Renamed archive'}})).status,200);assert.equal(all().find(r=>r.id===archiveProject.id).data.archived,true);for(const r of snapshot)assert.deepEqual(all().find(i=>i.id===r.id),r);assert.equal((await call('PATCH',{id:archiveProject.id,archived:false})).status,200);assert.equal(all().find(r=>r.id===archiveProject.id).data.status,'Ativo');
assert.equal((await call('DELETE',{id:archiveProject.id})).status,400);assert.equal((await call('DELETE',{id:archiveProject.id,confirmProject:true})).status,400);assert(all().some(r=>r.id===archiveProject.id));
user={admin:false,email:'finish@example.com',displayName:'Client'};assert.equal((await call('PATCH',{id:finishProject.id,archived:true})).status,403);assert.equal((await call('DELETE',{id:finishProject.id,confirmProject:true,confirmIrreversible:true})).status,403);user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
const unrelated=all().filter(r=>r.project===p2.id);const deleteFile='delete-project/file';await bucket.put(deleteFile,new Uint8Array([1,2]));await add('document',{title:'Delete file',file:deleteFile,visibility:'published'},finishProject.id);assert.equal((await call('DELETE',{id:finishProject.id,confirmProject:true,confirmIrreversible:true})).status,200);assert(!all().some(r=>r.id===finishProject.id||r.project===finishProject.id));assert(!stored.has(deleteFile));assert.deepEqual(all().filter(r=>r.project===p2.id),unrelated);assert(all().some(r=>r.id===c.id));console.log('PASS: archive/restore preserves project records; double confirmation and admin permissions; definitive deletion cascades records and files with project isolation.');

const financeApi=compile('app/api/finance/route.ts',{'@/lib/server':server,'@/lib/commercial':commercialModel,'@/lib/finance':financeModel});
async function financeAction(body){const res=await financeApi.POST(new Request('https://site.test/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}));return {status:res.status,...await res.json()};}
const fp=await add('project',{name:'Finance control',type:'Communication Audit'});const fc=await add('charge',{title:'Contract',amount:100000,due:'2026-11-10'},fp.id);const fr=await add('receipt',{charge:fc.id,amount:60000,date:'2026-09-01'},fp.id);await add('expense',{title:'General overhead',amount:10000,date:'2026-09-15'});await add('expense',{title:'Project cost',amount:5000,date:'2026-09-15'},fp.id);
assert.equal((await call('POST',{kind:'refund',project:fp.id,data:{amount:1}})).status,400);assert.equal((await financeAction({action:'refund',receipt:fr.id,amount:1,reason:'No confirmation'})).status,400);const refundBody={action:'refund',receipt:fr.id,amount:20000,date:'2026-09-20',reason:'Partial return',operationId:'finance-refund-unique-0001',cancelCharge:false,confirm:true};assert.equal((await financeAction(refundBody)).status,201);assert.equal((await financeAction(refundBody)).existing,true);assert.equal(all().filter(r=>r.kind==='refund'&&r.data.receipt===fr.id).length,1);assert.equal((await financeAction({...refundBody,cancelCharge:true})).status,409);assert.equal(financeModel.chargeTotals(all(),fc).balance,60000);assert.equal((await financeAction({...refundBody,operationId:'finance-refund-too-large',amount:40001})).status,400);assert.equal((await financeAction({...refundBody,operationId:'finance-refund-invalid-date',date:'2026-08-30'})).status,400);assert.equal((await financeAction({...refundBody,operationId:'finance-refund-future-date',date:'2099-01-01'})).status,400);
const refundRow=all().find(r=>r.kind==='refund'&&r.data.receipt===fr.id);assert.equal((await call('DELETE',{id:refundRow.id})).status,400);assert.equal((await call('PATCH',{id:refundRow.id,data:{amount:1}})).status,400);assert.equal(all().find(r=>r.id===fr.id).data.amount,60000,'Original receipt remains immutable');
const subset=all().filter(r=>r.id===fp.id||r.project===fp.id||r.kind==='expense'&&!r.project),sept=financeModel.financeSummary(subset,'2026-09','2026-10-06');assert.equal(sept.gross,60000);assert.equal(sept.returned,20000);assert.equal(sept.net,40000);assert.equal(sept.cost,15000);assert.equal(sept.profit,25000);assert.equal(sept.balance,0);const nov=financeModel.financeSummary(subset,'2026-11','2026-10-06');assert.equal(nov.future[0].total,60000);assert.equal(nov.balance,60000);
assert.equal((await financeAction({action:'cancel',charge:fc.id,reason:'Stopped service',confirm:true})).status,200);assert.equal(financeModel.chargeTotals(all(),all().find(r=>r.id===fc.id)).balance,0);assert.equal((await call('POST',{kind:'receipt',project:fp.id,data:{charge:fc.id,amount:1,date:'2026-10-06'}})).status,400);assert.equal((await call('PATCH',{id:fc.id,data:{amount:90000}})).status,400);assert.equal((await call('DELETE',{id:fc.id})).status,400);assert.equal(financeModel.financeSummary(all().filter(r=>r.project===fp.id),'2026-11','2026-10-06').future[0].total,0);
const second=await financeAction({...refundBody,operationId:'finance-refund-total-final',amount:40000,date:'2026-09-25',cancelCharge:true});assert.equal(second.status,201);assert.equal(financeModel.receiptNet(all(),fr),0);assert.equal((await financeAction({...refundBody,operationId:'finance-refund-exceeds-now',amount:1})).status,400);
const fpCharge=await add('charge',{title:'Another',amount:20000,due:'2026-12-01'},fp.id),fpReceipt=await add('receipt',{charge:fpCharge.id,amount:10000,date:'2026-09-02'},fp.id);assert.equal((await financeAction({...refundBody,receipt:fpReceipt.id,operationId:'finance-refund-and-cancel',amount:5000,cancelCharge:true})).status,201);assert(all().find(r=>r.id===fpCharge.id).data.cancelledAt);assert.equal(financeModel.chargeTotals(all(),all().find(r=>r.id===fpCharge.id)).balance,0);
await add('member',{name:'Finance client',email:'finance@example.com',approver:false},fp.id);user={admin:false,email:'finance@example.com',displayName:'Client'};assert.equal((await financeAction({action:'cancel',charge:fpCharge.id,reason:'Forbidden',confirm:true})).status,403);assert.equal((await financeAction({...refundBody,operationId:'finance-refund-client-denied'})).status,403);const financeView=await call('GET');assert(financeView.items.some(r=>r.kind==='refund'));assert(!financeView.items.some(r=>r.kind==='expense'));assert(!financeView.items.some(r=>r.kind==='refund'&&r.project!==fp.id));user={admin:true,email:'owner@example.com',displayName:'Gabriel'};
assert.equal(financeModel.businessDate('2026-10-01T01:00:00Z'),'2026-09-30');assert.equal(financeModel.addMonths('2026-12',1),'2027-01');assert.equal(financeModel.chargeTotals([{...fr,data:{...fr.data,amount:1}}],{...fc,data:{...fc.data,amount:1}}).balance,0);
console.log('PASS: financial cancellation, partial/full refunds, atomic balance guard, idempotency, immutable history, client isolation, monthly cash totals, future forecast, general expenses and Brazilian month boundaries.');

const atomicCharge=await add('charge',{title:'Concurrent guard',amount:10000,due:'2026-11-01'},fp.id),atomicReceipt=await add('receipt',{charge:atomicCharge.id,amount:10000,date:'2026-09-01'},fp.id),staleItems=all();await server.statement(server.record('refund',fp.id,{receipt:atomicReceipt.id,charge:atomicCharge.id,amount:9000,date:'2026-09-05',reason:'Earlier operation'})).run();const staleFinanceApi=compile('app/api/finance/route.ts',{'@/lib/server':{...server,context:async()=>({user,items:staleItems,projects:new Set()})},'@/lib/commercial':commercialModel,'@/lib/finance':financeModel});const guarded=await staleFinanceApi.POST(new Request('https://site.test/api/finance',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...refundBody,receipt:atomicReceipt.id,operationId:'finance-refund-stale-guard',amount:2000,cancelCharge:true})}));assert.equal(guarded.status,409);assert(!all().some(r=>r.id==='refund-finance-refund-stale-guard'));assert(!all().find(r=>r.id===atomicCharge.id).data.cancelledAt);assert.equal(financeModel.receiptNet(all(),atomicReceipt),1000);console.log('PASS: concurrent refund guard cannot over-refund or cancel a charge when the receipt balance changed.');
