import {ApiError,context,db,mutationOrigin,respondError,statement,activity} from '@/lib/server';
import {completionChecks,finalMaterials} from '@/lib/completion';
export const dynamic='force-dynamic';
export async function POST(req:Request){try{mutationOrigin(req);const {user,items}=await context();if(!user.admin)throw new ApiError(403,'Ação exclusiva do administrador.');const b:any=await req.json(),p=items.find(r=>r.kind==='project'&&r.id===b.project);if(!p)throw new ApiError(404,'Projeto não encontrado.');if(b.confirm!==true)throw new ApiError(400,'Confirme o encerramento.');if(p.data.status==='Concluído')return Response.json({ok:true,existing:true});if(p.data.status==='Cancelado')throw new ApiError(400,'Reative o projeto antes de concluir.');
 const text=(key:string,required=false)=>{const value=b[key];if(value!==undefined&&(typeof value!=='string'||value.length>30000))throw new ApiError(400,'Texto inválido.');if(required&&!value?.trim())throw new ApiError(400,'Preencha o resumo e as orientações da entrega final.');return (value||'').trim();};
 const completionSummary=text('completionSummary',true),handoverInstructions=text('handoverInstructions',true),nextSteps=text('nextSteps'),completionCaveats=text('completionCaveats'),checks=completionChecks(items,p.id);
 if(checks.some(r=>!r.done)&&!completionCaveats)throw new ApiError(400,'Registre o combinado sobre os itens pendentes antes de concluir.');
 const available=new Set(finalMaterials(items,p.id).map(r=>r.id));if(!Array.isArray(b.finalMaterialIds)||!b.finalMaterialIds.length||b.finalMaterialIds.length>500||b.finalMaterialIds.some((id:any)=>typeof id!=='string'||!available.has(id)))throw new ApiError(400,'Selecione materiais publicados deste projeto. Entregáveis precisam estar aprovados.');
 const data={...p.data,status:'Concluído',completedAt:new Date().toISOString(),completedBy:user.displayName,completionSummary,handoverInstructions,nextSteps,completionCaveats,completionChecks:checks,finalMaterialIds:[...new Set(b.finalMaterialIds)]};
 await db().batch([db().prepare('UPDATE records SET data=? WHERE id=?').bind(JSON.stringify(data),p.id),statement(activity(p.id,'Projeto concluído com entrega final registrada.',user.displayName))]);return Response.json({ok:true});}catch(e){return respondError(e);}}
